FROM container-registry.oracle.com/graalvm/native-image:21-ol8 AS builder
WORKDIR /build
COPY ./pom.xml /build/pom.xml
COPY ./src /build/src
COPY ./mvnw /build/mvnw
COPY ./.mvn /build/.mvn
RUN ./mvnw --no-transfer-progress native:compile -Pnative

FROM container-registry.oracle.com/os/oraclelinux:8-slim
EXPOSE 8080
EXPOSE 8081
COPY --from=builder /build/target/chatbot app
ENTRYPOINT ["/app"]